"""baseline

Revision ID: 47530de69031
Revises:
Create Date: 2026-05-21 12:35:38.017179

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47530de69031"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_prompts_id"), "ai_prompts", ["id"], unique=False)
    op.create_index(op.f("ix_ai_prompts_key"), "ai_prompts", ["key"], unique=True)
    op.create_table(
        "prospect_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(length=512), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prospect_questions_id"), "prospect_questions", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("picture", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("my_notes", sa.Text(), nullable=True),
        sa.Column("notes_log", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_company_name"),
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(
        op.f("ix_companies_user_id"), "companies", ["user_id"], unique=False
    )
    op.create_table(
        "cover_letter_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cover_letter_versions_id"),
        "cover_letter_versions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cover_letter_versions_user_id"),
        "cover_letter_versions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "cv_experiences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("employer", sa.String(length=255), nullable=False),
        sa.Column("employer_link", sa.String(length=512), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.String(length=64), nullable=True),
        sa.Column("end_date", sa.String(length=64), nullable=True),
        sa.Column("flag", sa.String(length=8), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("employment_type", sa.String(length=64), nullable=True),
        sa.Column("duration", sa.String(length=64), nullable=True),
        sa.Column("level", sa.String(length=64), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cv_experiences_id"), "cv_experiences", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_cv_experiences_user_id"), "cv_experiences", ["user_id"], unique=False
    )
    op.create_table(
        "cv_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("tagline", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cv_profiles_id"), "cv_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_cv_profiles_user_id"), "cv_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "cv_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cv_versions_id"), "cv_versions", ["id"], unique=False)
    op.create_index(
        op.f("ix_cv_versions_user_id"), "cv_versions", ["user_id"], unique=False
    )
    op.create_table(
        "learning_concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_learning_concepts_user_name"),
    )
    op.create_index(
        op.f("ix_learning_concepts_id"), "learning_concepts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_concepts_user_id"),
        "learning_concepts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "learning_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_topic", sa.String(length=512), nullable=True),
        sa.Column("notion_level", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_items_id"), "learning_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_items_user_id"), "learning_items", ["user_id"], unique=False
    )
    op.create_table(
        "learning_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_learning_tags_user_name"),
    )
    op.create_index(op.f("ix_learning_tags_id"), "learning_tags", ["id"], unique=False)
    op.create_index(
        op.f("ix_learning_tags_user_id"), "learning_tags", ["user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "recruiters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("agency", sa.String(length=255), nullable=True),
        sa.Column("my_notes", sa.Text(), nullable=True),
        sa.Column("notes_log", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "email", name="uq_user_recruiter_email"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_recruiter_name"),
    )
    op.create_index(op.f("ix_recruiters_id"), "recruiters", ["id"], unique=False)
    op.create_index(
        op.f("ix_recruiters_user_id"), "recruiters", ["user_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_role_name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_user_id"), "roles", ["user_id"], unique=False)
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("recruiter_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["recruiter_id"], ["recruiters.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_company_id"), "applications", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_created_at"), "applications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_applications_id"), "applications", ["id"], unique=False)
    op.create_index(
        op.f("ix_applications_recruiter_id"),
        "applications",
        ["recruiter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_role_id"), "applications", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_applications_uuid"), "applications", ["uuid"], unique=True)
    op.create_table(
        "company_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_notes_company_id"),
        "company_notes",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_notes_created_by"),
        "company_notes",
        ["created_by"],
        unique=False,
    )
    op.create_index(op.f("ix_company_notes_id"), "company_notes", ["id"], unique=False)
    op.create_index(
        op.f("ix_company_notes_user_id"), "company_notes", ["user_id"], unique=False
    )
    op.create_table(
        "concept_relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_concept_id", sa.Integer(), nullable=False),
        sa.Column("target_concept_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_concept_id"], ["learning_concepts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_concept_id"], ["learning_concepts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_concept_relationships_id"),
        "concept_relationships",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_relationships_source_concept_id"),
        "concept_relationships",
        ["source_concept_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_relationships_target_concept_id"),
        "concept_relationships",
        ["target_concept_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_concept_relationships_user_id"),
        "concept_relationships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "learning_item_concepts",
        sa.Column("learning_item_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("concept_type", sa.String(length=64), nullable=True),
        sa.Column("importance", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["learning_concepts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"], ["learning_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("learning_item_id", "concept_id"),
    )
    op.create_table(
        "learning_item_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("learning_item_id", sa.Integer(), nullable=False),
        sa.Column("ease", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["learning_item_id"], ["learning_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_item_reviews_id"),
        "learning_item_reviews",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_item_reviews_learning_item_id"),
        "learning_item_reviews",
        ["learning_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_item_reviews_user_id"),
        "learning_item_reviews",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "learning_item_tags",
        sa.Column("learning_item_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_item_id"], ["learning_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["learning_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("learning_item_id", "tag_id"),
    )
    op.create_table(
        "recruiter_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recruiter_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["recruiter_id"], ["recruiters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recruiter_notes_created_by"),
        "recruiter_notes",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruiter_notes_id"), "recruiter_notes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recruiter_notes_recruiter_id"),
        "recruiter_notes",
        ["recruiter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recruiter_notes_user_id"), "recruiter_notes", ["user_id"], unique=False
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_provider", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "application_id",
            "doc_type",
            "version",
            "format",
            name="uq_app_docs_type_version_format",
        ),
    )
    op.create_index(
        op.f("ix_application_documents_application_id"),
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_created_by"),
        "application_documents",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_id"),
        "application_documents",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_uuid"),
        "application_documents",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "application_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("stage_type", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("activity_type", sa.String(length=50), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_linkedin", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_events_id"), "application_events", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_application_events_stage_type"),
        "application_events",
        ["stage_type"],
        unique=False,
    )
    op.create_table(
        "application_job_descriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_job_descriptions_application_id"),
        "application_job_descriptions",
        ["application_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_application_job_descriptions_created_by"),
        "application_job_descriptions",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_job_descriptions_id"),
        "application_job_descriptions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "application_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_notes_application_id"),
        "application_notes",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_notes_created_by"),
        "application_notes",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_notes_id"), "application_notes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_application_notes_user_id"),
        "application_notes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "application_prospect_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=512), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_prospect_answers_application_id"),
        "application_prospect_answers",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_prospect_answers_id"),
        "application_prospect_answers",
        ["id"],
        unique=False,
    )
    op.create_table(
        "application_swot_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("strengths", sa.Text(), nullable=False),
        sa.Column("weaknesses", sa.Text(), nullable=False),
        sa.Column("opportunities", sa.Text(), nullable=False),
        sa.Column("threats", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_swot_analyses_application_id"),
        "application_swot_analyses",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_swot_analyses_id"),
        "application_swot_analyses",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_swot_analyses_id"), table_name="application_swot_analyses"
    )
    op.drop_index(
        op.f("ix_application_swot_analyses_application_id"),
        table_name="application_swot_analyses",
    )
    op.drop_table("application_swot_analyses")
    op.drop_index(
        op.f("ix_application_prospect_answers_id"),
        table_name="application_prospect_answers",
    )
    op.drop_index(
        op.f("ix_application_prospect_answers_application_id"),
        table_name="application_prospect_answers",
    )
    op.drop_table("application_prospect_answers")
    op.drop_index(op.f("ix_application_notes_user_id"), table_name="application_notes")
    op.drop_index(op.f("ix_application_notes_id"), table_name="application_notes")
    op.drop_index(
        op.f("ix_application_notes_created_by"), table_name="application_notes"
    )
    op.drop_index(
        op.f("ix_application_notes_application_id"), table_name="application_notes"
    )
    op.drop_table("application_notes")
    op.drop_index(
        op.f("ix_application_job_descriptions_id"),
        table_name="application_job_descriptions",
    )
    op.drop_index(
        op.f("ix_application_job_descriptions_created_by"),
        table_name="application_job_descriptions",
    )
    op.drop_index(
        op.f("ix_application_job_descriptions_application_id"),
        table_name="application_job_descriptions",
    )
    op.drop_table("application_job_descriptions")
    op.drop_index(
        op.f("ix_application_events_stage_type"), table_name="application_events"
    )
    op.drop_index(op.f("ix_application_events_id"), table_name="application_events")
    op.drop_table("application_events")
    op.drop_index(
        op.f("ix_application_documents_uuid"), table_name="application_documents"
    )
    op.drop_index(
        op.f("ix_application_documents_id"), table_name="application_documents"
    )
    op.drop_index(
        op.f("ix_application_documents_created_by"), table_name="application_documents"
    )
    op.drop_index(
        op.f("ix_application_documents_application_id"),
        table_name="application_documents",
    )
    op.drop_table("application_documents")
    op.drop_index(op.f("ix_recruiter_notes_user_id"), table_name="recruiter_notes")
    op.drop_index(op.f("ix_recruiter_notes_recruiter_id"), table_name="recruiter_notes")
    op.drop_index(op.f("ix_recruiter_notes_id"), table_name="recruiter_notes")
    op.drop_index(op.f("ix_recruiter_notes_created_by"), table_name="recruiter_notes")
    op.drop_table("recruiter_notes")
    op.drop_table("learning_item_tags")
    op.drop_index(
        op.f("ix_learning_item_reviews_user_id"), table_name="learning_item_reviews"
    )
    op.drop_index(
        op.f("ix_learning_item_reviews_learning_item_id"),
        table_name="learning_item_reviews",
    )
    op.drop_index(
        op.f("ix_learning_item_reviews_id"), table_name="learning_item_reviews"
    )
    op.drop_table("learning_item_reviews")
    op.drop_table("learning_item_concepts")
    op.drop_index(
        op.f("ix_concept_relationships_user_id"), table_name="concept_relationships"
    )
    op.drop_index(
        op.f("ix_concept_relationships_target_concept_id"),
        table_name="concept_relationships",
    )
    op.drop_index(
        op.f("ix_concept_relationships_source_concept_id"),
        table_name="concept_relationships",
    )
    op.drop_index(
        op.f("ix_concept_relationships_id"), table_name="concept_relationships"
    )
    op.drop_table("concept_relationships")
    op.drop_index(op.f("ix_company_notes_user_id"), table_name="company_notes")
    op.drop_index(op.f("ix_company_notes_id"), table_name="company_notes")
    op.drop_index(op.f("ix_company_notes_created_by"), table_name="company_notes")
    op.drop_index(op.f("ix_company_notes_company_id"), table_name="company_notes")
    op.drop_table("company_notes")
    op.drop_index(op.f("ix_applications_uuid"), table_name="applications")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_role_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_recruiter_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_created_at"), table_name="applications")
    op.drop_index(op.f("ix_applications_company_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_roles_user_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_recruiters_user_id"), table_name="recruiters")
    op.drop_index(op.f("ix_recruiters_id"), table_name="recruiters")
    op.drop_table("recruiters")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_learning_tags_user_id"), table_name="learning_tags")
    op.drop_index(op.f("ix_learning_tags_id"), table_name="learning_tags")
    op.drop_table("learning_tags")
    op.drop_index(op.f("ix_learning_items_user_id"), table_name="learning_items")
    op.drop_index(op.f("ix_learning_items_id"), table_name="learning_items")
    op.drop_table("learning_items")
    op.drop_index(op.f("ix_learning_concepts_user_id"), table_name="learning_concepts")
    op.drop_index(op.f("ix_learning_concepts_id"), table_name="learning_concepts")
    op.drop_table("learning_concepts")
    op.drop_index(op.f("ix_cv_versions_user_id"), table_name="cv_versions")
    op.drop_index(op.f("ix_cv_versions_id"), table_name="cv_versions")
    op.drop_table("cv_versions")
    op.drop_index(op.f("ix_cv_profiles_user_id"), table_name="cv_profiles")
    op.drop_index(op.f("ix_cv_profiles_id"), table_name="cv_profiles")
    op.drop_table("cv_profiles")
    op.drop_index(op.f("ix_cv_experiences_user_id"), table_name="cv_experiences")
    op.drop_index(op.f("ix_cv_experiences_id"), table_name="cv_experiences")
    op.drop_table("cv_experiences")
    op.drop_index(
        op.f("ix_cover_letter_versions_user_id"), table_name="cover_letter_versions"
    )
    op.drop_index(
        op.f("ix_cover_letter_versions_id"), table_name="cover_letter_versions"
    )
    op.drop_table("cover_letter_versions")
    op.drop_index(op.f("ix_companies_user_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_prospect_questions_id"), table_name="prospect_questions")
    op.drop_table("prospect_questions")
    op.drop_index(op.f("ix_ai_prompts_key"), table_name="ai_prompts")
    op.drop_index(op.f("ix_ai_prompts_id"), table_name="ai_prompts")
    op.drop_table("ai_prompts")
    # ### end Alembic commands ###
